<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("О компании");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:main.include",
	"",
	Array(
		"AREA_FILE_SHOW" => "file",
		"AREA_FILE_SUFFIX" => "inc",
		"EDIT_TEMPLATE" => "",
		"PATH" => "/local/include/about/about_main_text.php"
	)
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:main.include",
	"",
	Array(
		"AREA_FILE_SHOW" => "file",
		"AREA_FILE_SUFFIX" => "inc",
		"EDIT_TEMPLATE" => "",
		"PATH" => "/local/include/about/about_advantages_text.php"
	)
);?>

<?
$GLOBALS['filterBrandSlider'] = [
	'!DETAIL_PICTURE'=>false,
];

$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"about-brands-list", 
	array(
		"IMAGE_POSITION" => "left",
		"SHOW_CHILD_SECTIONS" => "",
		"DEPTH_LEVEL" => "1",
		"IS_AJAX" => "",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"IBLOCK_TYPE" => "aspro_max_content",
		"IBLOCK_ID" => "33",
		"NEWS_COUNT" => "18",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"FIELD_CODE" => array(
			0 => "CODE",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "SITE",
			1 => "PHONE",
			2 => "",
		),
		"DISPLAY_PANEL" => "",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "100000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_TEMPLATE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "",
		"DISPLAY_PREVIEW_TEXT" => "",
		"PREVIEW_TRUNCATE_LEN" => "0",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"USE_PERMISSIONS" => "N",
		"GROUP_PERMISSIONS" => array(
			0 => "1",
		),
		"SHOW_DETAIL_LINK" => "Y",
		"USE_FILTER"=> "Y",
		"FILTER_NAME" => "filterBrandSlider",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"CHECK_DATES" => "Y",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DETAIL_URL" => "/brands/#ELEMENT_CODE#/",
		"SECTION_URL" => "/brands/#SECTION_CODE_PATH#/",
		"IBLOCK_URL" => "/brands/",
		"INCLUDE_SUBSECTIONS" => "N",
		"BORDERED" => "Y",
		"SMALL_IMAGE_MODE" => "Y",
		"COMPONENT_TEMPLATE" => "about-brands-list",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"TITLE_BLOCK" => "Новости",
		"TITLE_BLOCK_ALL" => "Все новости",
		"ALL_URL" => "sale/",
		"INCLUDE_FILE" => "",
		"SHOW_SECTION_NAME" => "N",
		"BG_POSITION" => "top left",
		"SHOW_SUBSCRIBE" => "Y",
		"TITLE_SUBSCRIBE" => "Текст подписки",
		"HALF_BLOCK" => "N",
		"ALL_BLOCK_BG" => "N",
		"TYPE_IMG" => "md",
		"SIZE_IN_ROW" => "3",
		"FON_BLOCK_2_COLS" => "N",
		"USE_BG_IMAGE_ALTERNATE" => "N",
		"TITLE_SHOW_FON" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => ""
	),
	$component
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"about-clients-list", 
	array(
		"IBLOCK_TYPE" => "aspro_max_content",
		"IBLOCK_ID" => "52",
		"NEWS_COUNT" => "21",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "myFilter",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "URL_CLIENT",
			4 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "URL_CLIENT",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "/clients/#ELEMENT_CODE#/",
		"SECTION_URL" => "/clients/#SECTION_CODE#/",
		"IBLOCK_URL" => "/clients/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "0",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"IMG_POSITION" => "right",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "about-clients-list",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"TITLE_BLOCK" => "",
		"TITLE_BLOCK_ALL" => "",
		"ALL_URL" => "",
		"SIZE_IN_ROW" => "5",
		"TYPE_IMG" => "lg",
		"SHOW_SECTION_NAME" => "Y",
		"BORDERED" => "Y",
		"FON_BLOCK_2_COLS" => "N",
		"INCLUDE_FILE" => "",
		"SHOW_SUBSCRIBE" => "N",
		"TITLE_SUBSCRIBE" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "Y",
		"IS_AJAX" => "",
		"MESSAGE_404" => "",
		"USE_PERMISSIONS" => "N",
		"GROUP_PERMISSIONS" => array(
			0 => "1",
		),
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"BG_POSITION" => "top left",
		"HALF_BLOCK" => "N",
		"ALL_BLOCK_BG" => "N",
		"USE_BG_IMAGE_ALTERNATE" => "N",
		"TITLE_SHOW_FON" => "N",
		"FILE_404" => ""
	),
	$component
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"about-reviews-list", 
	array(
		"IBLOCK_TYPE" => "aspro_max_content",
		"IBLOCK_ID" => "53",
		"NEWS_COUNT" => "3",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "myFilter",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_TEXT",
			4 => "DETAIL_PICTURE",
			5 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "AUTHOR_WORK",
			1 => "AUTHOR_FIO",
			2 => "",
		),
		"CHECK_DATES" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "0",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"IMG_POSITION" => "right",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "about-reviews-list",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"TITLE_BLOCK" => "",
		"TITLE_BLOCK_ALL" => "",
		"ALL_URL" => "",
		"SIZE_IN_ROW" => "5",
		"TYPE_IMG" => "lg",
		"SHOW_SECTION_NAME" => "Y",
		"BORDERED" => "Y",
		"FON_BLOCK_2_COLS" => "N",
		"INCLUDE_FILE" => "",
		"SHOW_SUBSCRIBE" => "N",
		"TITLE_SUBSCRIBE" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "Y",
		"IS_AJAX" => "",
		"MESSAGE_404" => "",
		"USE_PERMISSIONS" => "N",
		"GROUP_PERMISSIONS" => array(
			0 => "1",
		),
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"BG_POSITION" => "top left",
		"HALF_BLOCK" => "N",
		"ALL_BLOCK_BG" => "N",
		"USE_BG_IMAGE_ALTERNATE" => "N",
		"TITLE_SHOW_FON" => "N",
		"FILE_404" => "",
		"DETAIL_URL" => ""
	),
	$component
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>