<?if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();?>

<?
$GLOBALS['filterNewsMain'] = [
    'SECTION_ID' => 853
];
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"front_sale", 
	array(
		"IBLOCK_TYPE" => "aspro_max_content",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "filterNewsMain",
		"IBLOCK_ID" => "23",
		"NEWS_COUNT" => "2",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DATE_ACTIVE_FROM",
			2 => "ACTIVE_TO",
			3 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "PERIOD",
			1 => "SALE_NUMBER",
			2 => "TIME_PROMO",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "ajax",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "front_sale",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"TITLE_BLOCK" => "Акции и выгодные предложения",
		"TITLE_BLOCK_ALL" => "Все акции",
		"ALL_URL" => "news/promo/",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"CHECK_REQUEST_BLOCK" => CMax::checkRequestBlock("sale"),
		"MOBILE_TEMPLATE" => $GLOBALS["arTheme"]["MOBILE_SALE"]["VALUE"],
		"NO_MARGIN" => "N",
		"TRANSPARENT" => "Y",
		"FILLED" => "N",
		"SIZE_IN_ROW" => "3",
		"TYPE_IMG" => "lg",
		"IS_AJAX" => CMax::checkAjaxRequest(),
		"MESSAGE_404" => "",
		"INCLUDE_FILE" => "",
		"IMG_POSITION" => "right",
		"BG_POSITION" => "top left"
	),
	false
);?>